package tts

import ()

type Voice struct {
	Id       string `json:"Id"`
	Name     string `json:"Name"`
	Gender   string `json:"Gender"`
	Language string `json:"Language"`
	Country  string `json:"Country"`
}

var Voices = []Voice{
	{Id: "voice-107", Name: "Andrew Multilingual", Gender: "Male", Language: "Multilingual", Country: "United States"},
	{Id: "voice-110", Name: "Ava Multilingual", Gender: "Female", Language: "Multilingual", Country: "United States"},
	{Id: "voice-112", Name: "Brian Multilingual", Gender: "Male", Language: "Multilingual", Country: "United States"},
	{Id: "voice-115", Name: "Emma Multilingual", Gender: "Female", Language: "Multilingual", Country: "United States"},
	{Id: "voice-142", Name: "Remy Multilingual", Gender: "Male", Language: "Multilingual", Country: "France"},
	{Id: "voice-143", Name: "Vivienne Multilingual", Gender: "Female", Language: "Multilingual", Country: "France"},
	{Id: "voice-154", Name: "Florian Multilingual", Gender: "Male", Language: "Multilingual", Country: "Germany"},
	{Id: "voice-157", Name: "Seraphina Multilingual", Gender: "Female", Language: "Multilingual", Country: "Germany"},
	{Id: "voice-177", Name: "Giuseppe Multilingual", Gender: "Male", Language: "Multilingual", Country: "Italy"},
	{Id: "voice-189", Name: "Hyunsu Multilingual", Gender: "Male", Language: "Multilingual", Country: "South Korea"},
	{Id: "voice-222", Name: "Thalita Multilingual", Gender: "Female", Language: "Multilingual", Country: "Brazil"},
	{Id: "voice-106", Name: "Ana", Gender: "Female", Language: "English", Country: "United States"},
	{Id: "voice-108", Name: "Andrew", Gender: "Male", Language: "English", Country: "United States"},
	{Id: "voice-109", Name: "Aria", Gender: "Female", Language: "English", Country: "United States"},
	{Id: "voice-111", Name: "Ava", Gender: "Female", Language: "English", Country: "United States"},
	{Id: "voice-113", Name: "Brian", Gender: "Male", Language: "English", Country: "United States"},
	{Id: "voice-114", Name: "Christopher", Gender: "Male", Language: "English", Country: "United States"},
	{Id: "voice-116", Name: "Emma", Gender: "Female", Language: "English", Country: "United States"},
	{Id: "voice-117", Name: "Eric", Gender: "Male", Language: "English", Country: "United States"},
	{Id: "voice-118", Name: "Guy", Gender: "Male", Language: "English", Country: "United States"},
	{Id: "voice-119", Name: "Jenny", Gender: "Female", Language: "English", Country: "United States"},
	{Id: "voice-120", Name: "Michelle", Gender: "Female", Language: "English", Country: "United States"},
	{Id: "voice-121", Name: "Roger", Gender: "Male", Language: "English", Country: "United States"},
	{Id: "voice-122", Name: "Steffan", Gender: "Male", Language: "English", Country: "United States"},
	{Id: "voice-82", Name: "Libby", Gender: "Female", Language: "English", Country: "United Kingdom"},
	{Id: "voice-83", Name: "Maisie", Gender: "Female", Language: "English", Country: "United Kingdom"},
	{Id: "voice-84", Name: "Ryan", Gender: "Male", Language: "English", Country: "United Kingdom"},
	{Id: "voice-85", Name: "Sonia", Gender: "Female", Language: "English", Country: "United Kingdom"},
	{Id: "voice-86", Name: "Thomas", Gender: "Male", Language: "English", Country: "United Kingdom"},
	{Id: "voice-78", Name: "Natasha", Gender: "Female", Language: "English", Country: "Australia"},
	{Id: "voice-79", Name: "William", Gender: "Male", Language: "English", Country: "Australia"},
	{Id: "voice-80", Name: "Clara", Gender: "Female", Language: "English", Country: "Canada"},
	{Id: "voice-81", Name: "Liam", Gender: "Male", Language: "English", Country: "Canada"},
	{Id: "voice-91", Name: "Neerja Expressive", Gender: "Female", Language: "English", Country: "India"},
	{Id: "voice-92", Name: "Neerja", Gender: "Female", Language: "English", Country: "India"},
	{Id: "voice-93", Name: "Prabhat", Gender: "Male", Language: "English", Country: "India"},
	{Id: "voice-87", Name: "Sam", Gender: "Male", Language: "English", Country: "Hong Kong"},
	{Id: "voice-88", Name: "Yan", Gender: "Female", Language: "English", Country: "Hong Kong"},
	{Id: "voice-89", Name: "Connor", Gender: "Male", Language: "English", Country: "Ireland"},
	{Id: "voice-90", Name: "Emily", Gender: "Female", Language: "English", Country: "Ireland"},
	{Id: "voice-94", Name: "Asilia", Gender: "Female", Language: "English", Country: "Kenya"},
	{Id: "voice-95", Name: "Chilemba", Gender: "Male", Language: "English", Country: "Kenya"},
	{Id: "voice-96", Name: "Abeo", Gender: "Male", Language: "English", Country: "Nigeria"},
	{Id: "voice-97", Name: "Ezinne", Gender: "Female", Language: "English", Country: "Nigeria"},
	{Id: "voice-98", Name: "Mitchell", Gender: "Male", Language: "English", Country: "New Zealand"},
	{Id: "voice-99", Name: "Molly", Gender: "Female", Language: "English", Country: "New Zealand"},
	{Id: "voice-100", Name: "James", Gender: "Male", Language: "English", Country: "Philippines"},
	{Id: "voice-101", Name: "Rosa", Gender: "Female", Language: "English", Country: "Philippines"},
	{Id: "voice-102", Name: "Luna", Gender: "Female", Language: "English", Country: "Singapore"},
	{Id: "voice-103", Name: "Wayne", Gender: "Male", Language: "English", Country: "Singapore"},
	{Id: "voice-104", Name: "Elimu", Gender: "Male", Language: "English", Country: "Tanzania"},
	{Id: "voice-105", Name: "Imani", Gender: "Female", Language: "English", Country: "Tanzania"},
	{Id: "voice-123", Name: "Leah", Gender: "Female", Language: "English", Country: "South Africa"},
	{Id: "voice-124", Name: "Luke", Gender: "Male", Language: "English", Country: "South Africa"},
	{Id: "voice-239", Name: "Elena", Gender: "Female", Language: "Spanish", Country: "Argentina"},
	{Id: "voice-240", Name: "Tomas", Gender: "Male", Language: "Spanish", Country: "Argentina"},
	{Id: "voice-241", Name: "Marcelo", Gender: "Male", Language: "Spanish", Country: "Bolivia"},
	{Id: "voice-242", Name: "Sofia", Gender: "Female", Language: "Spanish", Country: "Bolivia"},
	{Id: "voice-243", Name: "Catalina", Gender: "Female", Language: "Spanish", Country: "Chile"},
	{Id: "voice-244", Name: "Lorenzo", Gender: "Male", Language: "Spanish", Country: "Chile"},
	{Id: "voice-245", Name: "Gonzalo", Gender: "Male", Language: "Spanish", Country: "Colombia"},
	{Id: "voice-246", Name: "Salome", Gender: "Female", Language: "Spanish", Country: "Colombia"},
	{Id: "voice-247", Name: "Juan", Gender: "Male", Language: "Spanish", Country: "Costa Rica"},
	{Id: "voice-248", Name: "Maria", Gender: "Female", Language: "Spanish", Country: "Costa Rica"},
	{Id: "voice-249", Name: "Belkys", Gender: "Female", Language: "Spanish", Country: "Cuba"},
	{Id: "voice-250", Name: "Manuel", Gender: "Male", Language: "Spanish", Country: "Cuba"},
	{Id: "voice-251", Name: "Emilio", Gender: "Male", Language: "Spanish", Country: "Dominican Republic"},
	{Id: "voice-252", Name: "Ramona", Gender: "Female", Language: "Spanish", Country: "Dominican Republic"},
	{Id: "voice-253", Name: "Andrea", Gender: "Female", Language: "Spanish", Country: "Ecuador"},
	{Id: "voice-254", Name: "Luis", Gender: "Male", Language: "Spanish", Country: "Ecuador"},
	{Id: "voice-255", Name: "Alvaro", Gender: "Male", Language: "Spanish", Country: "Spain"},
	{Id: "voice-256", Name: "Elvira", Gender: "Female", Language: "Spanish", Country: "Spain"},
	{Id: "voice-257", Name: "Ximena", Gender: "Female", Language: "Spanish", Country: "Spain"},
	{Id: "voice-258", Name: "Javier", Gender: "Male", Language: "Spanish", Country: "Equatorial Guinea"},
	{Id: "voice-259", Name: "Teresa", Gender: "Female", Language: "Spanish", Country: "Equatorial Guinea"},
	{Id: "voice-260", Name: "Andres", Gender: "Male", Language: "Spanish", Country: "Guatemala"},
	{Id: "voice-261", Name: "Marta", Gender: "Female", Language: "Spanish", Country: "Guatemala"},
	{Id: "voice-262", Name: "Carlos", Gender: "Male", Language: "Spanish", Country: "Honduras"},
	{Id: "voice-263", Name: "Karla", Gender: "Female", Language: "Spanish", Country: "Honduras"},
	{Id: "voice-264", Name: "Dalia", Gender: "Female", Language: "Spanish", Country: "Mexico"},
	{Id: "voice-265", Name: "Jorge", Gender: "Male", Language: "Spanish", Country: "Mexico"},
	{Id: "voice-266", Name: "Federico", Gender: "Male", Language: "Spanish", Country: "Nicaragua"},
	{Id: "voice-267", Name: "Yolanda", Gender: "Female", Language: "Spanish", Country: "Nicaragua"},
	{Id: "voice-268", Name: "Margarita", Gender: "Female", Language: "Spanish", Country: "Panama"},
	{Id: "voice-269", Name: "Roberto", Gender: "Male", Language: "Spanish", Country: "Panama"},
	{Id: "voice-270", Name: "Alex", Gender: "Male", Language: "Spanish", Country: "Peru"},
	{Id: "voice-271", Name: "Camila", Gender: "Female", Language: "Spanish", Country: "Peru"},
	{Id: "voice-272", Name: "Karina", Gender: "Female", Language: "Spanish", Country: "Puerto Rico"},
	{Id: "voice-273", Name: "Victor", Gender: "Male", Language: "Spanish", Country: "Puerto Rico"},
	{Id: "voice-274", Name: "Mario", Gender: "Male", Language: "Spanish", Country: "Paraguay"},
	{Id: "voice-275", Name: "Tania", Gender: "Female", Language: "Spanish", Country: "Paraguay"},
	{Id: "voice-276", Name: "Lorena", Gender: "Female", Language: "Spanish", Country: "El Salvador"},
	{Id: "voice-277", Name: "Rodrigo", Gender: "Male", Language: "Spanish", Country: "El Salvador"},
	{Id: "voice-278", Name: "Alonso", Gender: "Male", Language: "Spanish", Country: "United States"},
	{Id: "voice-279", Name: "Paloma", Gender: "Female", Language: "Spanish", Country: "United States"},
	{Id: "voice-280", Name: "Mateo", Gender: "Male", Language: "Spanish", Country: "Uruguay"},
	{Id: "voice-281", Name: "Valentina", Gender: "Female", Language: "Spanish", Country: "Uruguay"},
	{Id: "voice-282", Name: "Paola", Gender: "Female", Language: "Spanish", Country: "Venezuela"},
	{Id: "voice-283", Name: "Sebastian", Gender: "Male", Language: "Spanish", Country: "Venezuela"},
	{Id: "voice-53", Name: "Xiaoxiao", Gender: "Female", Language: "Chinese", Country: "China"},
	{Id: "voice-54", Name: "Xiaoyi", Gender: "Female", Language: "Chinese", Country: "China"},
	{Id: "voice-55", Name: "Yunjian", Gender: "Male", Language: "Chinese", Country: "China"},
	{Id: "voice-56", Name: "Yunxi", Gender: "Male", Language: "Chinese", Country: "China"},
	{Id: "voice-57", Name: "Yunxia", Gender: "Male", Language: "Chinese", Country: "China"},
	{Id: "voice-58", Name: "Yunyang", Gender: "Male", Language: "Chinese", Country: "China"},
	{Id: "voice-59", Name: "Xiaobei", Gender: "Female", Language: "Chinese", Country: "China"},
	{Id: "voice-60", Name: "Xiaoni", Gender: "Female", Language: "Chinese", Country: "China"},
	{Id: "voice-61", Name: "HiuGaai", Gender: "Female", Language: "Chinese", Country: "Hong Kong"},
	{Id: "voice-62", Name: "HiuMaan", Gender: "Female", Language: "Chinese", Country: "Hong Kong"},
	{Id: "voice-63", Name: "WanLung", Gender: "Male", Language: "Chinese", Country: "Hong Kong"},
	{Id: "voice-64", Name: "HsiaoChen", Gender: "Female", Language: "Chinese", Country: "Taiwan"},
	{Id: "voice-65", Name: "HsiaoYu", Gender: "Female", Language: "Chinese", Country: "Taiwan"},
	{Id: "voice-66", Name: "YunJhe", Gender: "Male", Language: "Chinese", Country: "Taiwan"},
	{Id: "voice-131", Name: "Charline", Gender: "Female", Language: "French", Country: "Belgium"},
	{Id: "voice-132", Name: "Gerard", Gender: "Male", Language: "French", Country: "Belgium"},
	{Id: "voice-133", Name: "Antoine", Gender: "Male", Language: "French", Country: "Canada"},
	{Id: "voice-134", Name: "Jean", Gender: "Male", Language: "French", Country: "Canada"},
	{Id: "voice-135", Name: "Sylvie", Gender: "Female", Language: "French", Country: "Canada"},
	{Id: "voice-136", Name: "Thierry", Gender: "Male", Language: "French", Country: "Canada"},
	{Id: "voice-137", Name: "Ariane", Gender: "Female", Language: "French", Country: "Switzerland"},
	{Id: "voice-138", Name: "Fabrice", Gender: "Male", Language: "French", Country: "Switzerland"},
	{Id: "voice-139", Name: "Denise", Gender: "Female", Language: "French", Country: "France"},
	{Id: "voice-140", Name: "Eloise", Gender: "Female", Language: "French", Country: "France"},
	{Id: "voice-141", Name: "Henri", Gender: "Male", Language: "French", Country: "France"},
	{Id: "voice-148", Name: "Ingrid", Gender: "Female", Language: "German", Country: "Austria"},
	{Id: "voice-149", Name: "Jonas", Gender: "Male", Language: "German", Country: "Austria"},
	{Id: "voice-150", Name: "Jan", Gender: "Male", Language: "German", Country: "Switzerland"},
	{Id: "voice-151", Name: "Leni", Gender: "Female", Language: "German", Country: "Switzerland"},
	{Id: "voice-152", Name: "Amala", Gender: "Female", Language: "German", Country: "Germany"},
	{Id: "voice-153", Name: "Conrad", Gender: "Male", Language: "German", Country: "Germany"},
	{Id: "voice-155", Name: "Katja", Gender: "Female", Language: "German", Country: "Germany"},
	{Id: "voice-156", Name: "Killian", Gender: "Male", Language: "German", Country: "Germany"},
	{Id: "voice-7", Name: "Fatima", Gender: "Female", Language: "Arabic", Country: "United Arab Emirates"},
	{Id: "voice-8", Name: "Hamdan", Gender: "Male", Language: "Arabic", Country: "United Arab Emirates"},
	{Id: "voice-9", Name: "Ali", Gender: "Male", Language: "Arabic", Country: "Bahrain"},
	{Id: "voice-10", Name: "Laila", Gender: "Female", Language: "Arabic", Country: "Bahrain"},
	{Id: "voice-11", Name: "Amina", Gender: "Female", Language: "Arabic", Country: "Algeria"},
	{Id: "voice-12", Name: "Ismael", Gender: "Male", Language: "Arabic", Country: "Algeria"},
	{Id: "voice-13", Name: "Salma", Gender: "Female", Language: "Arabic", Country: "Egypt"},
	{Id: "voice-14", Name: "Shakir", Gender: "Male", Language: "Arabic", Country: "Egypt"},
	{Id: "voice-15", Name: "Bassel", Gender: "Male", Language: "Arabic", Country: "Iraq"},
	{Id: "voice-16", Name: "Rana", Gender: "Female", Language: "Arabic", Country: "Iraq"},
	{Id: "voice-17", Name: "Sana", Gender: "Female", Language: "Arabic", Country: "Jordan"},
	{Id: "voice-18", Name: "Taim", Gender: "Male", Language: "Arabic", Country: "Jordan"},
	{Id: "voice-19", Name: "Fahed", Gender: "Male", Language: "Arabic", Country: "Kuwait"},
	{Id: "voice-20", Name: "Noura", Gender: "Female", Language: "Arabic", Country: "Kuwait"},
	{Id: "voice-21", Name: "Layla", Gender: "Female", Language: "Arabic", Country: "Lebanon"},
	{Id: "voice-22", Name: "Rami", Gender: "Male", Language: "Arabic", Country: "Lebanon"},
	{Id: "voice-23", Name: "Iman", Gender: "Female", Language: "Arabic", Country: "Libya"},
	{Id: "voice-24", Name: "Omar", Gender: "Male", Language: "Arabic", Country: "Libya"},
	{Id: "voice-25", Name: "Jamal", Gender: "Male", Language: "Arabic", Country: "Morocco"},
	{Id: "voice-26", Name: "Mouna", Gender: "Female", Language: "Arabic", Country: "Morocco"},
	{Id: "voice-27", Name: "Abdullah", Gender: "Male", Language: "Arabic", Country: "Oman"},
	{Id: "voice-28", Name: "Aysha", Gender: "Female", Language: "Arabic", Country: "Oman"},
	{Id: "voice-29", Name: "Amal", Gender: "Female", Language: "Arabic", Country: "Qatar"},
	{Id: "voice-30", Name: "Moaz", Gender: "Male", Language: "Arabic", Country: "Qatar"},
	{Id: "voice-31", Name: "Hamed", Gender: "Male", Language: "Arabic", Country: "Saudi Arabia"},
	{Id: "voice-32", Name: "Zariyah", Gender: "Female", Language: "Arabic", Country: "Saudi Arabia"},
	{Id: "voice-33", Name: "Amany", Gender: "Female", Language: "Arabic", Country: "Syria"},
	{Id: "voice-34", Name: "Laith", Gender: "Male", Language: "Arabic", Country: "Syria"},
	{Id: "voice-35", Name: "Hedi", Gender: "Male", Language: "Arabic", Country: "Tunisia"},
	{Id: "voice-36", Name: "Reem", Gender: "Female", Language: "Arabic", Country: "Tunisia"},
	{Id: "voice-37", Name: "Maryam", Gender: "Female", Language: "Arabic", Country: "Yemen"},
	{Id: "voice-38", Name: "Saleh", Gender: "Male", Language: "Arabic", Country: "Yemen"},
	{Id: "voice-1", Name: "Adri", Gender: "Female", Language: "Afrikaans", Country: "South Africa"},
	{Id: "voice-2", Name: "Willem", Gender: "Male", Language: "Afrikaans", Country: "South Africa"},
	{Id: "voice-3", Name: "Anila", Gender: "Female", Language: "Albanian", Country: "Albania"},
	{Id: "voice-4", Name: "Ilir", Gender: "Male", Language: "Albanian", Country: "Albania"},
	{Id: "voice-5", Name: "Ameha", Gender: "Male", Language: "Amharic", Country: "Ethiopia"},
	{Id: "voice-6", Name: "Mekdes", Gender: "Female", Language: "Amharic", Country: "Ethiopia"},
	{Id: "voice-39", Name: "Babek", Gender: "Male", Language: "Azerbaijani", Country: "Azerbaijan"},
	{Id: "voice-40", Name: "Banu", Gender: "Female", Language: "Azerbaijani", Country: "Azerbaijan"},
	{Id: "voice-41", Name: "Nabanita", Gender: "Female", Language: "Bengali", Country: "Bangladesh"},
	{Id: "voice-42", Name: "Pradeep", Gender: "Male", Language: "Bengali", Country: "Bangladesh"},
	{Id: "voice-43", Name: "Bashkar", Gender: "Male", Language: "Bengali", Country: "India"},
	{Id: "voice-44", Name: "Tanishaa", Gender: "Female", Language: "Bengali", Country: "India"},
	{Id: "voice-45", Name: "Goran", Gender: "Male", Language: "Bosnian", Country: "Bosnia and Herzegovina"},
	{Id: "voice-46", Name: "Vesna", Gender: "Female", Language: "Bosnian", Country: "Bosnia and Herzegovina"},
	{Id: "voice-47", Name: "Borislav", Gender: "Male", Language: "Bulgarian", Country: "Bulgaria"},
	{Id: "voice-48", Name: "Kalina", Gender: "Female", Language: "Bulgarian", Country: "Bulgaria"},
	{Id: "voice-49", Name: "Nilar", Gender: "Female", Language: "Burmese", Country: "Myanmar"},
	{Id: "voice-50", Name: "Thiha", Gender: "Male", Language: "Burmese", Country: "Myanmar"},
	{Id: "voice-51", Name: "Enric", Gender: "Male", Language: "Catalan", Country: "Spain"},
	{Id: "voice-52", Name: "Joana", Gender: "Female", Language: "Catalan", Country: "Spain"},
	{Id: "voice-67", Name: "Gabrijela", Gender: "Female", Language: "Croatian", Country: "Croatia"},
	{Id: "voice-68", Name: "Srecko", Gender: "Male", Language: "Croatian", Country: "Croatia"},
	{Id: "voice-69", Name: "Antonin", Gender: "Male", Language: "Czech", Country: "Czech Republic"},
	{Id: "voice-70", Name: "Vlasta", Gender: "Female", Language: "Czech", Country: "Czech Republic"},
	{Id: "voice-71", Name: "Christel", Gender: "Female", Language: "Danish", Country: "Denmark"},
	{Id: "voice-72", Name: "Jeppe", Gender: "Male", Language: "Danish", Country: "Denmark"},
	{Id: "voice-73", Name: "Arnaud", Gender: "Male", Language: "Dutch", Country: "Belgium"},
	{Id: "voice-74", Name: "Dena", Gender: "Female", Language: "Dutch", Country: "Belgium"},
	{Id: "voice-75", Name: "Colette", Gender: "Female", Language: "Dutch", Country: "Netherlands"},
	{Id: "voice-76", Name: "Fenna", Gender: "Female", Language: "Dutch", Country: "Netherlands"},
	{Id: "voice-77", Name: "Maarten", Gender: "Male", Language: "Dutch", Country: "Netherlands"},
	{Id: "voice-125", Name: "Anu", Gender: "Female", Language: "Estonian", Country: "Estonia"},
	{Id: "voice-126", Name: "Kert", Gender: "Male", Language: "Estonian", Country: "Estonia"},
	{Id: "voice-127", Name: "Angelo", Gender: "Male", Language: "Filipino", Country: "Philippines"},
	{Id: "voice-128", Name: "Blessica", Gender: "Female", Language: "Filipino", Country: "Philippines"},
	{Id: "voice-129", Name: "Harri", Gender: "Male", Language: "Finnish", Country: "Finland"},
	{Id: "voice-130", Name: "Noora", Gender: "Female", Language: "Finnish", Country: "Finland"},
	{Id: "voice-144", Name: "Roi", Gender: "Male", Language: "Galician", Country: "Spain"},
	{Id: "voice-145", Name: "Sabela", Gender: "Female", Language: "Galician", Country: "Spain"},
	{Id: "voice-146", Name: "Eka", Gender: "Female", Language: "Georgian", Country: "Georgia"},
	{Id: "voice-147", Name: "Giorgi", Gender: "Male", Language: "Georgian", Country: "Georgia"},
	{Id: "voice-158", Name: "Athina", Gender: "Female", Language: "Greek", Country: "Greece"},
	{Id: "voice-159", Name: "Nestoras", Gender: "Male", Language: "Greek", Country: "Greece"},
	{Id: "voice-160", Name: "Nestoras", Gender: "Male", Language: "Greek", Country: "Greece"},
	{Id: "voice-161", Name: "Dhwani", Gender: "Female", Language: "Gujarati", Country: "India"},
	{Id: "voice-162", Name: "Niranjan", Gender: "Male", Language: "Gujarati", Country: "India"},
	{Id: "voice-163", Name: "Avri", Gender: "Male", Language: "Hebrew", Country: "Israel"},
	{Id: "voice-164", Name: "Hila", Gender: "Female", Language: "Hebrew", Country: "Israel"},
	{Id: "voice-165", Name: "Madhur", Gender: "Male", Language: "Hindi", Country: "India"},
	{Id: "voice-166", Name: "Swara", Gender: "Female", Language: "Hindi", Country: "India"},
	{Id: "voice-167", Name: "Noemi", Gender: "Female", Language: "Hungarian", Country: "Hungary"},
	{Id: "voice-168", Name: "Tamas", Gender: "Male", Language: "Hungarian", Country: "Hungary"},
	{Id: "voice-169", Name: "Gudrun", Gender: "Female", Language: "Icelandic", Country: "Iceland"},
	{Id: "voice-170", Name: "Gunnar", Gender: "Male", Language: "Icelandic", Country: "Iceland"},
	{Id: "voice-171", Name: "Ardi", Gender: "Male", Language: "Indonesian", Country: "Indonesia"},
	{Id: "voice-172", Name: "Gadis", Gender: "Female", Language: "Indonesian", Country: "Indonesia"},
	{Id: "voice-173", Name: "Colm", Gender: "Male", Language: "Irish", Country: "Ireland"},
	{Id: "voice-174", Name: "Orla", Gender: "Female", Language: "Irish", Country: "Ireland"},
	{Id: "voice-175", Name: "Diego", Gender: "Male", Language: "Italian", Country: "Italy"},
	{Id: "voice-176", Name: "Elsa", Gender: "Female", Language: "Italian", Country: "Italy"},
	{Id: "voice-178", Name: "Isabella", Gender: "Female", Language: "Italian", Country: "Italy"},
	{Id: "voice-179", Name: "Keita", Gender: "Male", Language: "Japanese", Country: "Japan"},
	{Id: "voice-180", Name: "Nanami", Gender: "Female", Language: "Japanese", Country: "Japan"},
	{Id: "voice-181", Name: "Dimas", Gender: "Male", Language: "Javanese", Country: "Indonesia"},
	{Id: "voice-182", Name: "Siti", Gender: "Female", Language: "Javanese", Country: "Indonesia"},
	{Id: "voice-183", Name: "Gagan", Gender: "Male", Language: "Kannada", Country: "India"},
	{Id: "voice-184", Name: "Sapna", Gender: "Female", Language: "Kannada", Country: "India"},
	{Id: "voice-185", Name: "Aigul", Gender: "Female", Language: "Kazakh", Country: "Kazakhstan"},
	{Id: "voice-186", Name: "Daulet", Gender: "Male", Language: "Kazakh", Country: "Kazakhstan"},
	{Id: "voice-187", Name: "Piseth", Gender: "Male", Language: "Khmer", Country: "Cambodia"},
	{Id: "voice-188", Name: "Sreymom", Gender: "Female", Language: "Khmer", Country: "Cambodia"},
	{Id: "voice-190", Name: "InJoon", Gender: "Male", Language: "Korean", Country: "South Korea"},
	{Id: "voice-191", Name: "SunHi", Gender: "Female", Language: "Korean", Country: "South Korea"},
	{Id: "voice-192", Name: "Chanthavong", Gender: "Male", Language: "Lao", Country: "Laos"},
	{Id: "voice-193", Name: "Keomany", Gender: "Female", Language: "Lao", Country: "Laos"},
	{Id: "voice-194", Name: "Everita", Gender: "Female", Language: "Latvian", Country: "Latvia"},
	{Id: "voice-195", Name: "Nils", Gender: "Male", Language: "Latvian", Country: "Latvia"},
	{Id: "voice-196", Name: "Leonas", Gender: "Male", Language: "Lithuanian", Country: "Lithuania"},
	{Id: "voice-197", Name: "Ona", Gender: "Female", Language: "Lithuanian", Country: "Lithuania"},
	{Id: "voice-198", Name: "Aleksandar", Gender: "Male", Language: "Macedonian", Country: "North Macedonia"},
	{Id: "voice-199", Name: "Marija", Gender: "Female", Language: "Macedonian", Country: "North Macedonia"},
	{Id: "voice-200", Name: "Osman", Gender: "Male", Language: "Malay", Country: "Malaysia"},
	{Id: "voice-201", Name: "Yasmin", Gender: "Female", Language: "Malay", Country: "Malaysia"},
	{Id: "voice-202", Name: "Midhun", Gender: "Male", Language: "Malayalam", Country: "India"},
	{Id: "voice-203", Name: "Sobhana", Gender: "Female", Language: "Malayalam", Country: "India"},
	{Id: "voice-204", Name: "Grace", Gender: "Female", Language: "Maltese", Country: "Malta"},
	{Id: "voice-205", Name: "Joseph", Gender: "Male", Language: "Maltese", Country: "Malta"},
	{Id: "voice-206", Name: "Aarohi", Gender: "Female", Language: "Marathi", Country: "India"},
	{Id: "voice-207", Name: "Manohar", Gender: "Male", Language: "Marathi", Country: "India"},
	{Id: "voice-208", Name: "Bataa", Gender: "Male", Language: "Mongolian", Country: "Mongolia"},
	{Id: "voice-209", Name: "Yesui", Gender: "Female", Language: "Mongolian", Country: "Mongolia"},
	{Id: "voice-210", Name: "Hemkala", Gender: "Female", Language: "Nepali", Country: "Nepal"},
	{Id: "voice-211", Name: "Sagar", Gender: "Male", Language: "Nepali", Country: "Nepal"},
	{Id: "voice-212", Name: "Finn", Gender: "Male", Language: "Norwegian", Country: "Norway"},
	{Id: "voice-213", Name: "Pernille", Gender: "Female", Language: "Norwegian", Country: "Norway"},
	{Id: "voice-214", Name: "GulNawaz", Gender: "Male", Language: "Pashto", Country: "Afghanistan"},
	{Id: "voice-215", Name: "Latifa", Gender: "Female", Language: "Pashto", Country: "Afghanistan"},
	{Id: "voice-216", Name: "Dilara", Gender: "Female", Language: "Persian", Country: "Iran"},
	{Id: "voice-217", Name: "Farid", Gender: "Male", Language: "Persian", Country: "Iran"},
	{Id: "voice-218", Name: "Marek", Gender: "Male", Language: "Polish", Country: "Poland"},
	{Id: "voice-219", Name: "Zofia", Gender: "Female", Language: "Polish", Country: "Poland"},
	{Id: "voice-220", Name: "Antonio", Gender: "Male", Language: "Portuguese", Country: "Brazil"},
	{Id: "voice-221", Name: "Francisca", Gender: "Female", Language: "Portuguese", Country: "Brazil"},
	{Id: "voice-223", Name: "Duarte", Gender: "Male", Language: "Portuguese", Country: "Portugal"},
	{Id: "voice-224", Name: "Raquel", Gender: "Female", Language: "Portuguese", Country: "Portugal"},
	{Id: "voice-225", Name: "Alina", Gender: "Female", Language: "Romanian", Country: "Romania"},
	{Id: "voice-226", Name: "Emil", Gender: "Male", Language: "Romanian", Country: "Romania"},
	{Id: "voice-227", Name: "Dmitry", Gender: "Male", Language: "Russian", Country: "Russia"},
	{Id: "voice-228", Name: "Svetlana", Gender: "Female", Language: "Russian", Country: "Russia"},
	{Id: "voice-229", Name: "Nicholas", Gender: "Male", Language: "Serbian", Country: "Serbia"},
	{Id: "voice-230", Name: "Sophie", Gender: "Female", Language: "Serbian", Country: "Serbia"},
	{Id: "voice-231", Name: "Sameera", Gender: "Male", Language: "Sinhala", Country: "Sri Lanka"},
	{Id: "voice-232", Name: "Thilini", Gender: "Female", Language: "Sinhala", Country: "Sri Lanka"},
	{Id: "voice-233", Name: "Lukas", Gender: "Male", Language: "Slovak", Country: "Slovakia"},
	{Id: "voice-234", Name: "Viktoria", Gender: "Female", Language: "Slovak", Country: "Slovakia"},
	{Id: "voice-235", Name: "Petra", Gender: "Female", Language: "Slovenian", Country: "Slovenia"},
	{Id: "voice-236", Name: "Rok", Gender: "Male", Language: "Slovenian", Country: "Slovenia"},
	{Id: "voice-237", Name: "Muuse", Gender: "Male", Language: "Somali", Country: "Somalia"},
	{Id: "voice-238", Name: "Ubax", Gender: "Female", Language: "Somali", Country: "Somalia"},
	{Id: "voice-284", Name: "Jajang", Gender: "Male", Language: "Sundanese", Country: "Indonesia"},
	{Id: "voice-285", Name: "Tuti", Gender: "Female", Language: "Sundanese", Country: "Indonesia"},
	{Id: "voice-286", Name: "Rafiki", Gender: "Male", Language: "Swahili", Country: "Kenya"},
	{Id: "voice-287", Name: "Zuri", Gender: "Female", Language: "Swahili", Country: "Kenya"},
	{Id: "voice-288", Name: "Daudi", Gender: "Male", Language: "Swahili", Country: "Tanzania"},
	{Id: "voice-289", Name: "Rehema", Gender: "Female", Language: "Swahili", Country: "Tanzania"},
	{Id: "voice-290", Name: "Mattias", Gender: "Male", Language: "Swedish", Country: "Sweden"},
	{Id: "voice-291", Name: "Sofie", Gender: "Female", Language: "Swedish", Country: "Sweden"},
	{Id: "voice-292", Name: "Pallavi", Gender: "Female", Language: "Tamil", Country: "India"},
	{Id: "voice-293", Name: "Valluvar", Gender: "Male", Language: "Tamil", Country: "India"},
	{Id: "voice-294", Name: "Kumar", Gender: "Male", Language: "Tamil", Country: "Sri Lanka"},
	{Id: "voice-295", Name: "Saranya", Gender: "Female", Language: "Tamil", Country: "Sri Lanka"},
	{Id: "voice-296", Name: "Kani", Gender: "Female", Language: "Tamil", Country: "Malaysia"},
	{Id: "voice-297", Name: "Surya", Gender: "Male", Language: "Tamil", Country: "Malaysia"},
	{Id: "voice-298", Name: "Anbu", Gender: "Male", Language: "Tamil", Country: "Singapore"},
	{Id: "voice-299", Name: "Venba", Gender: "Female", Language: "Tamil", Country: "Singapore"},
	{Id: "voice-300", Name: "Mohan", Gender: "Male", Language: "Telugu", Country: "India"},
	{Id: "voice-301", Name: "Shruti", Gender: "Female", Language: "Telugu", Country: "India"},
	{Id: "voice-302", Name: "Niwat", Gender: "Male", Language: "Thai", Country: "Thailand"},
	{Id: "voice-303", Name: "Premwadee", Gender: "Female", Language: "Thai", Country: "Thailand"},
	{Id: "voice-304", Name: "Ahmet", Gender: "Male", Language: "Turkish", Country: "Turkey"},
	{Id: "voice-305", Name: "Emel", Gender: "Female", Language: "Turkish", Country: "Turkey"},
	{Id: "voice-306", Name: "Ostap", Gender: "Male", Language: "Ukrainian", Country: "Ukraine"},
	{Id: "voice-307", Name: "Polina", Gender: "Female", Language: "Ukrainian", Country: "Ukraine"},
	{Id: "voice-308", Name: "Gul", Gender: "Female", Language: "Urdu", Country: "India"},
	{Id: "voice-309", Name: "Salman", Gender: "Male", Language: "Urdu", Country: "India"},
	{Id: "voice-310", Name: "Asad", Gender: "Male", Language: "Urdu", Country: "Pakistan"},
	{Id: "voice-311", Name: "Uzma", Gender: "Female", Language: "Urdu", Country: "Pakistan"},
	{Id: "voice-312", Name: "Madina", Gender: "Female", Language: "Uzbek", Country: "Uzbekistan"},
	{Id: "voice-313", Name: "Sardor", Gender: "Male", Language: "Uzbek", Country: "Uzbekistan"},
	{Id: "voice-314", Name: "HoaiMy", Gender: "Female", Language: "Vietnamese", Country: "Vietnam"},
	{Id: "voice-315", Name: "NamMinh", Gender: "Male", Language: "Vietnamese", Country: "Vietnam"},
	{Id: "voice-316", Name: "Aled", Gender: "Male", Language: "Welsh", Country: "United Kingdom"},
	{Id: "voice-317", Name: "Nia", Gender: "Female", Language: "Welsh", Country: "United Kingdom"},
	{Id: "voice-318", Name: "Thando", Gender: "Female", Language: "Zulu", Country: "South Africa"},
	{Id: "voice-319", Name: "Themba", Gender: "Male", Language: "Zulu", Country: "South Africa"},
	// Spanish Voices (voice-320 to voice-330)
	{Id: "voice-320", Name: "Andrew Spanish", Gender: "Male", Language: "Spanish", Country: "United States"},
	{Id: "voice-321", Name: "Ava Spanish", Gender: "Female", Language: "Spanish", Country: "United States"},
	{Id: "voice-322", Name: "Brian Spanish", Gender: "Male", Language: "Spanish", Country: "United States"},
	{Id: "voice-323", Name: "Emma Spanish", Gender: "Female", Language: "Spanish", Country: "United States"},
	{Id: "voice-324", Name: "Remy Spanish", Gender: "Male", Language: "Spanish", Country: "France"},
	{Id: "voice-325", Name: "Vivienne Spanish", Gender: "Female", Language: "Spanish", Country: "France"},
	{Id: "voice-326", Name: "Florian Spanish", Gender: "Male", Language: "Spanish", Country: "Germany"},
	{Id: "voice-327", Name: "Seraphina Spanish", Gender: "Female", Language: "Spanish", Country: "Germany"},
	{Id: "voice-328", Name: "Giuseppe Spanish", Gender: "Male", Language: "Spanish", Country: "Italy"},
	{Id: "voice-329", Name: "Hyunsu Spanish", Gender: "Male", Language: "Spanish", Country: "South Korea"},
	{Id: "voice-330", Name: "Thalita Spanish", Gender: "Female", Language: "Spanish", Country: "Brazil"},

	// French Voices (voice-331 to voice-341)
	{Id: "voice-331", Name: "Andrew French", Gender: "Male", Language: "French", Country: "United States"},
	{Id: "voice-332", Name: "Ava French", Gender: "Female", Language: "French", Country: "United States"},
	{Id: "voice-333", Name: "Brian French", Gender: "Male", Language: "French", Country: "United States"},
	{Id: "voice-334", Name: "Emma French", Gender: "Female", Language: "French", Country: "United States"},
	{Id: "voice-335", Name: "Remy French", Gender: "Male", Language: "French", Country: "France"},
	{Id: "voice-336", Name: "Vivienne French", Gender: "Female", Language: "French", Country: "France"},
	{Id: "voice-337", Name: "Florian French", Gender: "Male", Language: "French", Country: "Germany"},
	{Id: "voice-338", Name: "Seraphina French", Gender: "Female", Language: "French", Country: "Germany"},
	{Id: "voice-339", Name: "Giuseppe French", Gender: "Male", Language: "French", Country: "Italy"},
	{Id: "voice-340", Name: "Hyunsu French", Gender: "Male", Language: "French", Country: "South Korea"},
	{Id: "voice-341", Name: "Thalita French", Gender: "Female", Language: "French", Country: "Brazil"},

	// German Voices (voice-342 to voice-352)
	{Id: "voice-342", Name: "Andrew German", Gender: "Male", Language: "German", Country: "United States"},
	{Id: "voice-343", Name: "Ava German", Gender: "Female", Language: "German", Country: "United States"},
	{Id: "voice-344", Name: "Brian German", Gender: "Male", Language: "German", Country: "United States"},
	{Id: "voice-345", Name: "Emma German", Gender: "Female", Language: "German", Country: "United States"},
	{Id: "voice-346", Name: "Remy German", Gender: "Male", Language: "German", Country: "France"},
	{Id: "voice-347", Name: "Vivienne German", Gender: "Female", Language: "German", Country: "France"},
	{Id: "voice-348", Name: "Florian German", Gender: "Male", Language: "German", Country: "Germany"},
	{Id: "voice-349", Name: "Seraphina German", Gender: "Female", Language: "German", Country: "Germany"},
	{Id: "voice-350", Name: "Giuseppe German", Gender: "Male", Language: "German", Country: "Italy"},
	{Id: "voice-351", Name: "Hyunsu German", Gender: "Male", Language: "German", Country: "South Korea"},
	{Id: "voice-352", Name: "Thalita German", Gender: "Female", Language: "German", Country: "Brazil"},

	// Italian Voices (voice-353 to voice-363)
	{Id: "voice-353", Name: "Andrew Italian", Gender: "Male", Language: "Italian", Country: "United States"},
	{Id: "voice-354", Name: "Ava Italian", Gender: "Female", Language: "Italian", Country: "United States"},
	{Id: "voice-355", Name: "Brian Italian", Gender: "Male", Language: "Italian", Country: "United States"},
	{Id: "voice-356", Name: "Emma Italian", Gender: "Female", Language: "Italian", Country: "United States"},
	{Id: "voice-357", Name: "Remy Italian", Gender: "Male", Language: "Italian", Country: "France"},
	{Id: "voice-358", Name: "Vivienne Italian", Gender: "Female", Language: "Italian", Country: "France"},
	{Id: "voice-359", Name: "Florian Italian", Gender: "Male", Language: "Italian", Country: "Germany"},
	{Id: "voice-360", Name: "Seraphina Italian", Gender: "Female", Language: "Italian", Country: "Germany"},
	{Id: "voice-361", Name: "Giuseppe Italian", Gender: "Male", Language: "Italian", Country: "Italy"},
	{Id: "voice-362", Name: "Hyunsu Italian", Gender: "Male", Language: "Italian", Country: "South Korea"},
	{Id: "voice-363", Name: "Thalita Italian", Gender: "Female", Language: "Italian", Country: "Brazil"},

	// Portuguese Voices (voice-364 to voice-374)
	{Id: "voice-364", Name: "Andrew Portuguese", Gender: "Male", Language: "Portuguese", Country: "United States"},
	{Id: "voice-365", Name: "Ava Portuguese", Gender: "Female", Language: "Portuguese", Country: "United States"},
	{Id: "voice-366", Name: "Brian Portuguese", Gender: "Male", Language: "Portuguese", Country: "United States"},
	{Id: "voice-367", Name: "Emma Portuguese", Gender: "Female", Language: "Portuguese", Country: "United States"},
	{Id: "voice-368", Name: "Remy Portuguese", Gender: "Male", Language: "Portuguese", Country: "France"},
	{Id: "voice-369", Name: "Vivienne Portuguese", Gender: "Female", Language: "Portuguese", Country: "France"},
	{Id: "voice-370", Name: "Florian Portuguese", Gender: "Male", Language: "Portuguese", Country: "Germany"},
	{Id: "voice-371", Name: "Seraphina Portuguese", Gender: "Female", Language: "Portuguese", Country: "Germany"},
	{Id: "voice-372", Name: "Giuseppe Portuguese", Gender: "Male", Language: "Portuguese", Country: "Italy"},
	{Id: "voice-373", Name: "Hyunsu Portuguese", Gender: "Male", Language: "Portuguese", Country: "South Korea"},
	{Id: "voice-374", Name: "Thalita Portuguese", Gender: "Female", Language: "Portuguese", Country: "Brazil"},

	// Korean Voices (voice-375 to voice-385)
	{Id: "voice-375", Name: "Andrew Korean", Gender: "Male", Language: "Korean", Country: "United States"},
	{Id: "voice-376", Name: "Ava Korean", Gender: "Female", Language: "Korean", Country: "United States"},
	{Id: "voice-377", Name: "Brian Korean", Gender: "Male", Language: "Korean", Country: "United States"},
	{Id: "voice-378", Name: "Emma Korean", Gender: "Female", Language: "Korean", Country: "United States"},
	{Id: "voice-379", Name: "Remy Korean", Gender: "Male", Language: "Korean", Country: "France"},
	{Id: "voice-380", Name: "Vivienne Korean", Gender: "Female", Language: "Korean", Country: "France"},
	{Id: "voice-381", Name: "Florian Korean", Gender: "Male", Language: "Korean", Country: "Germany"},
	{Id: "voice-382", Name: "Seraphina Korean", Gender: "Female", Language: "Korean", Country: "Germany"},
	{Id: "voice-383", Name: "Giuseppe Korean", Gender: "Male", Language: "Korean", Country: "Italy"},
	{Id: "voice-384", Name: "Hyunsu Korean", Gender: "Male", Language: "Korean", Country: "South Korea"},
	{Id: "voice-385", Name: "Thalita Korean", Gender: "Female", Language: "Korean", Country: "Brazil"},

	// Chinese Voices (voice-386 to voice-396)
	{Id: "voice-386", Name: "Andrew Chinese", Gender: "Male", Language: "Chinese", Country: "United States"},
	{Id: "voice-387", Name: "Ava Chinese", Gender: "Female", Language: "Chinese", Country: "United States"},
	{Id: "voice-388", Name: "Brian Chinese", Gender: "Male", Language: "Chinese", Country: "United States"},
	{Id: "voice-389", Name: "Emma Chinese", Gender: "Female", Language: "Chinese", Country: "United States"},
	{Id: "voice-390", Name: "Remy Chinese", Gender: "Male", Language: "Chinese", Country: "France"},
	{Id: "voice-391", Name: "Vivienne Chinese", Gender: "Female", Language: "Chinese", Country: "France"},
	{Id: "voice-392", Name: "Florian Chinese", Gender: "Male", Language: "Chinese", Country: "Germany"},
	{Id: "voice-393", Name: "Seraphina Chinese", Gender: "Female", Language: "Chinese", Country: "Germany"},
	{Id: "voice-394", Name: "Giuseppe Chinese", Gender: "Male", Language: "Chinese", Country: "Italy"},
	{Id: "voice-395", Name: "Hyunsu Chinese", Gender: "Male", Language: "Chinese", Country: "South Korea"},
	{Id: "voice-396", Name: "Thalita Chinese", Gender: "Female", Language: "Chinese", Country: "Brazil"},

	// Japanese Voices (voice-397 to voice-407)
	{Id: "voice-397", Name: "Andrew Japanese", Gender: "Male", Language: "Japanese", Country: "United States"},
	{Id: "voice-398", Name: "Ava Japanese", Gender: "Female", Language: "Japanese", Country: "United States"},
	{Id: "voice-399", Name: "Brian Japanese", Gender: "Male", Language: "Japanese", Country: "United States"},
	{Id: "voice-400", Name: "Emma Japanese", Gender: "Female", Language: "Japanese", Country: "United States"},
	{Id: "voice-401", Name: "Remy Japanese", Gender: "Male", Language: "Japanese", Country: "France"},
	{Id: "voice-402", Name: "Vivienne Japanese", Gender: "Female", Language: "Japanese", Country: "France"},
	{Id: "voice-403", Name: "Florian Japanese", Gender: "Male", Language: "Japanese", Country: "Germany"},
	{Id: "voice-404", Name: "Seraphina Japanese", Gender: "Female", Language: "Japanese", Country: "Germany"},
	{Id: "voice-405", Name: "Giuseppe Japanese", Gender: "Male", Language: "Japanese", Country: "Italy"},
	{Id: "voice-406", Name: "Hyunsu Japanese", Gender: "Male", Language: "Japanese", Country: "South Korea"},
	{Id: "voice-407", Name: "Thalita Japanese", Gender: "Female", Language: "Japanese", Country: "Brazil"},

	// Arabic Voices (voice-408 to voice-418)
	{Id: "voice-408", Name: "Andrew Arabic", Gender: "Male", Language: "Arabic", Country: "United States"},
	{Id: "voice-409", Name: "Ava Arabic", Gender: "Female", Language: "Arabic", Country: "United States"},
	{Id: "voice-410", Name: "Brian Arabic", Gender: "Male", Language: "Arabic", Country: "United States"},
	{Id: "voice-411", Name: "Emma Arabic", Gender: "Female", Language: "Arabic", Country: "United States"},
	{Id: "voice-412", Name: "Remy Arabic", Gender: "Male", Language: "Arabic", Country: "France"},
	{Id: "voice-413", Name: "Vivienne Arabic", Gender: "Female", Language: "Arabic", Country: "France"},
	{Id: "voice-414", Name: "Florian Arabic", Gender: "Male", Language: "Arabic", Country: "Germany"},
	{Id: "voice-415", Name: "Seraphina Arabic", Gender: "Female", Language: "Arabic", Country: "Germany"},
	{Id: "voice-416", Name: "Giuseppe Arabic", Gender: "Male", Language: "Arabic", Country: "Italy"},
	{Id: "voice-417", Name: "Hyunsu Arabic", Gender: "Male", Language: "Arabic", Country: "South Korea"},
	{Id: "voice-418", Name: "Thalita Arabic", Gender: "Female", Language: "Arabic", Country: "Brazil"},

	// Hindi Voices (voice-419 to voice-429)
	{Id: "voice-419", Name: "Andrew Hindi", Gender: "Male", Language: "Hindi", Country: "United States"},
	{Id: "voice-420", Name: "Ava Hindi", Gender: "Female", Language: "Hindi", Country: "United States"},
	{Id: "voice-421", Name: "Brian Hindi", Gender: "Male", Language: "Hindi", Country: "United States"},
	{Id: "voice-422", Name: "Emma Hindi", Gender: "Female", Language: "Hindi", Country: "United States"},
	{Id: "voice-423", Name: "Remy Hindi", Gender: "Male", Language: "Hindi", Country: "France"},
	{Id: "voice-424", Name: "Vivienne Hindi", Gender: "Female", Language: "Hindi", Country: "France"},
	{Id: "voice-425", Name: "Florian Hindi", Gender: "Male", Language: "Hindi", Country: "Germany"},
	{Id: "voice-426", Name: "Seraphina Hindi", Gender: "Female", Language: "Hindi", Country: "Germany"},
	{Id: "voice-427", Name: "Giuseppe Hindi", Gender: "Male", Language: "Hindi", Country: "Italy"},
	{Id: "voice-428", Name: "Hyunsu Hindi", Gender: "Male", Language: "Hindi", Country: "South Korea"},
	{Id: "voice-429", Name: "Thalita Hindi", Gender: "Female", Language: "Hindi", Country: "Brazil"},

	// Russian Voices (voice-430 to voice-440)
	{Id: "voice-430", Name: "Andrew Russian", Gender: "Male", Language: "Russian", Country: "United States"},
	{Id: "voice-431", Name: "Ava Russian", Gender: "Female", Language: "Russian", Country: "United States"},
	{Id: "voice-432", Name: "Brian Russian", Gender: "Male", Language: "Russian", Country: "United States"},
	{Id: "voice-433", Name: "Emma Russian", Gender: "Female", Language: "Russian", Country: "United States"},
	{Id: "voice-434", Name: "Remy Russian", Gender: "Male", Language: "Russian", Country: "France"},
	{Id: "voice-435", Name: "Vivienne Russian", Gender: "Female", Language: "Russian", Country: "France"},
	{Id: "voice-436", Name: "Florian Russian", Gender: "Male", Language: "Russian", Country: "Germany"},
	{Id: "voice-437", Name: "Seraphina Russian", Gender: "Female", Language: "Russian", Country: "Germany"},
	{Id: "voice-438", Name: "Giuseppe Russian", Gender: "Male", Language: "Russian", Country: "Italy"},
	{Id: "voice-439", Name: "Hyunsu Russian", Gender: "Male", Language: "Russian", Country: "South Korea"},
	{Id: "voice-440", Name: "Thalita Russian", Gender: "Female", Language: "Russian", Country: "Brazil"},

	// Dutch Voices (voice-441 to voice-451)
	{Id: "voice-441", Name: "Andrew Dutch", Gender: "Male", Language: "Dutch", Country: "United States"},
	{Id: "voice-442", Name: "Ava Dutch", Gender: "Female", Language: "Dutch", Country: "United States"},
	{Id: "voice-443", Name: "Brian Dutch", Gender: "Male", Language: "Dutch", Country: "United States"},
	{Id: "voice-444", Name: "Emma Dutch", Gender: "Female", Language: "Dutch", Country: "United States"},
	{Id: "voice-445", Name: "Remy Dutch", Gender: "Male", Language: "Dutch", Country: "France"},
	{Id: "voice-446", Name: "Vivienne Dutch", Gender: "Female", Language: "Dutch", Country: "France"},
	{Id: "voice-447", Name: "Florian Dutch", Gender: "Male", Language: "Dutch", Country: "Germany"},
	{Id: "voice-448", Name: "Seraphina Dutch", Gender: "Female", Language: "Dutch", Country: "Germany"},
	{Id: "voice-449", Name: "Giuseppe Dutch", Gender: "Male", Language: "Dutch", Country: "Italy"},
	{Id: "voice-450", Name: "Hyunsu Dutch", Gender: "Male", Language: "Dutch", Country: "South Korea"},
	{Id: "voice-451", Name: "Thalita Dutch", Gender: "Female", Language: "Dutch", Country: "Brazil"},

	// Swedish Voices (voice-452 to voice-462)
	{Id: "voice-452", Name: "Andrew Swedish", Gender: "Male", Language: "Swedish", Country: "United States"},
	{Id: "voice-453", Name: "Ava Swedish", Gender: "Female", Language: "Swedish", Country: "United States"},
	{Id: "voice-454", Name: "Brian Swedish", Gender: "Male", Language: "Swedish", Country: "United States"},
	{Id: "voice-455", Name: "Emma Swedish", Gender: "Female", Language: "Swedish", Country: "United States"},
	{Id: "voice-456", Name: "Remy Swedish", Gender: "Male", Language: "Swedish", Country: "France"},
	{Id: "voice-457", Name: "Vivienne Swedish", Gender: "Female", Language: "Swedish", Country: "France"},
	{Id: "voice-458", Name: "Florian Swedish", Gender: "Male", Language: "Swedish", Country: "Germany"},
	{Id: "voice-459", Name: "Seraphina Swedish", Gender: "Female", Language: "Swedish", Country: "Germany"},
	{Id: "voice-460", Name: "Giuseppe Swedish", Gender: "Male", Language: "Swedish", Country: "Italy"},
	{Id: "voice-461", Name: "Hyunsu Swedish", Gender: "Male", Language: "Swedish", Country: "South Korea"},
	{Id: "voice-462", Name: "Thalita Swedish", Gender: "Female", Language: "Swedish", Country: "Brazil"},

	// Norwegian Voices (voice-463 to voice-473)
	{Id: "voice-463", Name: "Andrew Norwegian", Gender: "Male", Language: "Norwegian", Country: "United States"},
	{Id: "voice-464", Name: "Ava Norwegian", Gender: "Female", Language: "Norwegian", Country: "United States"},
	{Id: "voice-465", Name: "Brian Norwegian", Gender: "Male", Language: "Norwegian", Country: "United States"},
	{Id: "voice-466", Name: "Emma Norwegian", Gender: "Female", Language: "Norwegian", Country: "United States"},
	{Id: "voice-467", Name: "Remy Norwegian", Gender: "Male", Language: "Norwegian", Country: "France"},
	{Id: "voice-468", Name: "Vivienne Norwegian", Gender: "Female", Language: "Norwegian", Country: "France"},
	{Id: "voice-469", Name: "Florian Norwegian", Gender: "Male", Language: "Norwegian", Country: "Germany"},
	{Id: "voice-470", Name: "Seraphina Norwegian", Gender: "Female", Language: "Norwegian", Country: "Germany"},
	{Id: "voice-471", Name: "Giuseppe Norwegian", Gender: "Male", Language: "Norwegian", Country: "Italy"},
	{Id: "voice-472", Name: "Hyunsu Norwegian", Gender: "Male", Language: "Norwegian", Country: "South Korea"},
	{Id: "voice-473", Name: "Thalita Norwegian", Gender: "Female", Language: "Norwegian", Country: "Brazil"},

	// Danish Voices (voice-474 to voice-484)
	{Id: "voice-474", Name: "Andrew Danish", Gender: "Male", Language: "Danish", Country: "United States"},
	{Id: "voice-475", Name: "Ava Danish", Gender: "Female", Language: "Danish", Country: "United States"},
	{Id: "voice-476", Name: "Brian Danish", Gender: "Male", Language: "Danish", Country: "United States"},
	{Id: "voice-477", Name: "Emma Danish", Gender: "Female", Language: "Danish", Country: "United States"},
	{Id: "voice-478", Name: "Remy Danish", Gender: "Male", Language: "Danish", Country: "France"},
	{Id: "voice-479", Name: "Vivienne Danish", Gender: "Female", Language: "Danish", Country: "France"},
	{Id: "voice-480", Name: "Florian Danish", Gender: "Male", Language: "Danish", Country: "Germany"},
	{Id: "voice-481", Name: "Seraphina Danish", Gender: "Female", Language: "Danish", Country: "Germany"},
	{Id: "voice-482", Name: "Giuseppe Danish", Gender: "Male", Language: "Danish", Country: "Italy"},
	{Id: "voice-483", Name: "Hyunsu Danish", Gender: "Male", Language: "Danish", Country: "South Korea"},
	{Id: "voice-484", Name: "Thalita Danish", Gender: "Female", Language: "Danish", Country: "Brazil"},

	// Turkish Voices (voice-485 to voice-495)
	{Id: "voice-485", Name: "Andrew Turkish", Gender: "Male", Language: "Turkish", Country: "United States"},
	{Id: "voice-486", Name: "Ava Turkish", Gender: "Female", Language: "Turkish", Country: "United States"},
	{Id: "voice-487", Name: "Brian Turkish", Gender: "Male", Language: "Turkish", Country: "United States"},
	{Id: "voice-488", Name: "Emma Turkish", Gender: "Female", Language: "Turkish", Country: "United States"},
	{Id: "voice-489", Name: "Remy Turkish", Gender: "Male", Language: "Turkish", Country: "France"},
	{Id: "voice-490", Name: "Vivienne Turkish", Gender: "Female", Language: "Turkish", Country: "France"},
	{Id: "voice-491", Name: "Florian Turkish", Gender: "Male", Language: "Turkish", Country: "Germany"},
	{Id: "voice-492", Name: "Seraphina Turkish", Gender: "Female", Language: "Turkish", Country: "Germany"},
	{Id: "voice-493", Name: "Giuseppe Turkish", Gender: "Male", Language: "Turkish", Country: "Italy"},
	{Id: "voice-494", Name: "Hyunsu Turkish", Gender: "Male", Language: "Turkish", Country: "South Korea"},
	{Id: "voice-495", Name: "Thalita Turkish", Gender: "Female", Language: "Turkish", Country: "Brazil"},

	// Polish Voices (voice-496 to voice-506)
	{Id: "voice-496", Name: "Andrew Polish", Gender: "Male", Language: "Polish", Country: "United States"},
	{Id: "voice-497", Name: "Ava Polish", Gender: "Female", Language: "Polish", Country: "United States"},
	{Id: "voice-498", Name: "Brian Polish", Gender: "Male", Language: "Polish", Country: "United States"},
	{Id: "voice-499", Name: "Emma Polish", Gender: "Female", Language: "Polish", Country: "United States"},
	{Id: "voice-500", Name: "Remy Polish", Gender: "Male", Language: "Polish", Country: "France"},
	{Id: "voice-501", Name: "Vivienne Polish", Gender: "Female", Language: "Polish", Country: "France"},
	{Id: "voice-502", Name: "Florian Polish", Gender: "Male", Language: "Polish", Country: "Germany"},
	{Id: "voice-503", Name: "Seraphina Polish", Gender: "Female", Language: "Polish", Country: "Germany"},
	{Id: "voice-504", Name: "Giuseppe Polish", Gender: "Male", Language: "Polish", Country: "Italy"},
	{Id: "voice-505", Name: "Hyunsu Polish", Gender: "Male", Language: "Polish", Country: "South Korea"},
	{Id: "voice-506", Name: "Thalita Polish", Gender: "Female", Language: "Polish", Country: "Brazil"},

	// Romanian Voices (voice-507 to voice-517)
	{Id: "voice-507", Name: "Andrew Romanian", Gender: "Male", Language: "Romanian", Country: "United States"},
	{Id: "voice-508", Name: "Ava Romanian", Gender: "Female", Language: "Romanian", Country: "United States"},
	{Id: "voice-509", Name: "Brian Romanian", Gender: "Male", Language: "Romanian", Country: "United States"},
	{Id: "voice-510", Name: "Emma Romanian", Gender: "Female", Language: "Romanian", Country: "United States"},
	{Id: "voice-511", Name: "Remy Romanian", Gender: "Male", Language: "Romanian", Country: "France"},
	{Id: "voice-512", Name: "Vivienne Romanian", Gender: "Female", Language: "Romanian", Country: "France"},
	{Id: "voice-513", Name: "Florian Romanian", Gender: "Male", Language: "Romanian", Country: "Germany"},
	{Id: "voice-514", Name: "Seraphina Romanian", Gender: "Female", Language: "Romanian", Country: "Germany"},
	{Id: "voice-515", Name: "Giuseppe Romanian", Gender: "Male", Language: "Romanian", Country: "Italy"},
	{Id: "voice-516", Name: "Hyunsu Romanian", Gender: "Male", Language: "Romanian", Country: "South Korea"},
	{Id: "voice-517", Name: "Thalita Romanian", Gender: "Female", Language: "Romanian", Country: "Brazil"},

	// Hungarian Voices (voice-518 to voice-528)
	{Id: "voice-518", Name: "Andrew Hungarian", Gender: "Male", Language: "Hungarian", Country: "United States"},
	{Id: "voice-519", Name: "Ava Hungarian", Gender: "Female", Language: "Hungarian", Country: "United States"},
	{Id: "voice-520", Name: "Brian Hungarian", Gender: "Male", Language: "Hungarian", Country: "United States"},
	{Id: "voice-521", Name: "Emma Hungarian", Gender: "Female", Language: "Hungarian", Country: "United States"},
	{Id: "voice-522", Name: "Remy Hungarian", Gender: "Male", Language: "Hungarian", Country: "France"},
	{Id: "voice-523", Name: "Vivienne Hungarian", Gender: "Female", Language: "Hungarian", Country: "France"},
	{Id: "voice-524", Name: "Florian Hungarian", Gender: "Male", Language: "Hungarian", Country: "Germany"},
	{Id: "voice-525", Name: "Seraphina Hungarian", Gender: "Female", Language: "Hungarian", Country: "Germany"},
	{Id: "voice-526", Name: "Giuseppe Hungarian", Gender: "Male", Language: "Hungarian", Country: "Italy"},
	{Id: "voice-527", Name: "Hyunsu Hungarian", Gender: "Male", Language: "Hungarian", Country: "South Korea"},
	{Id: "voice-528", Name: "Thalita Hungarian", Gender: "Female", Language: "Hungarian", Country: "Brazil"},

	// Greek Voices (voice-529 to voice-539)
	{Id: "voice-529", Name: "Andrew Greek", Gender: "Male", Language: "Greek", Country: "United States"},
	{Id: "voice-530", Name: "Ava Greek", Gender: "Female", Language: "Greek", Country: "United States"},
	{Id: "voice-531", Name: "Brian Greek", Gender: "Male", Language: "Greek", Country: "United States"},
	{Id: "voice-532", Name: "Emma Greek", Gender: "Female", Language: "Greek", Country: "United States"},
	{Id: "voice-533", Name: "Remy Greek", Gender: "Male", Language: "Greek", Country: "France"},
	{Id: "voice-534", Name: "Vivienne Greek", Gender: "Female", Language: "Greek", Country: "France"},
	{Id: "voice-535", Name: "Florian Greek", Gender: "Male", Language: "Greek", Country: "Germany"},
	{Id: "voice-536", Name: "Seraphina Greek", Gender: "Female", Language: "Greek", Country: "Germany"},
	{Id: "voice-537", Name: "Giuseppe Greek", Gender: "Male", Language: "Greek", Country: "Italy"},
	{Id: "voice-538", Name: "Hyunsu Greek", Gender: "Male", Language: "Greek", Country: "South Korea"},
	{Id: "voice-539", Name: "Thalita Greek", Gender: "Female", Language: "Greek", Country: "Brazil"},

	// Indonesian Voices (voice-540 to voice-550)
	{Id: "voice-540", Name: "Andrew Indonesian", Gender: "Male", Language: "Indonesian", Country: "United States"},
	{Id: "voice-541", Name: "Ava Indonesian", Gender: "Female", Language: "Indonesian", Country: "United States"},
	{Id: "voice-542", Name: "Brian Indonesian", Gender: "Male", Language: "Indonesian", Country: "United States"},
	{Id: "voice-543", Name: "Emma Indonesian", Gender: "Female", Language: "Indonesian", Country: "United States"},
	{Id: "voice-544", Name: "Remy Indonesian", Gender: "Male", Language: "Indonesian", Country: "France"},
	{Id: "voice-545", Name: "Vivienne Indonesian", Gender: "Female", Language: "Indonesian", Country: "France"},
	{Id: "voice-546", Name: "Florian Indonesian", Gender: "Male", Language: "Indonesian", Country: "Germany"},
	{Id: "voice-547", Name: "Seraphina Indonesian", Gender: "Female", Language: "Indonesian", Country: "Germany"},
	{Id: "voice-548", Name: "Giuseppe Indonesian", Gender: "Male", Language: "Indonesian", Country: "Italy"},
	{Id: "voice-549", Name: "Hyunsu Indonesian", Gender: "Male", Language: "Indonesian", Country: "South Korea"},
	{Id: "voice-550", Name: "Thalita Indonesian", Gender: "Female", Language: "Indonesian", Country: "Brazil"},

	// Urdu Voices (voice-551 to voice-561)
	{Id: "voice-551", Name: "Andrew Urdu", Gender: "Male", Language: "Urdu", Country: "United States"},
	{Id: "voice-552", Name: "Ava Urdu", Gender: "Female", Language: "Urdu", Country: "United States"},
	{Id: "voice-553", Name: "Brian Urdu", Gender: "Male", Language: "Urdu", Country: "United States"},
	{Id: "voice-554", Name: "Emma Urdu", Gender: "Female", Language: "Urdu", Country: "United States"},
	{Id: "voice-555", Name: "Remy Urdu", Gender: "Male", Language: "Urdu", Country: "France"},
	{Id: "voice-556", Name: "Vivienne Urdu", Gender: "Female", Language: "Urdu", Country: "France"},
	{Id: "voice-557", Name: "Florian Urdu", Gender: "Male", Language: "Urdu", Country: "Germany"},
	{Id: "voice-558", Name: "Seraphina Urdu", Gender: "Female", Language: "Urdu", Country: "Germany"},
	{Id: "voice-559", Name: "Giuseppe Urdu", Gender: "Male", Language: "Urdu", Country: "Italy"},
	{Id: "voice-560", Name: "Hyunsu Urdu", Gender: "Male", Language: "Urdu", Country: "South Korea"},
	{Id: "voice-561", Name: "Thalita Urdu", Gender: "Female", Language: "Urdu", Country: "Brazil"},

	// Filipino Voices (voice-562 to voice-572)
	{Id: "voice-562", Name: "Andrew Filipino", Gender: "Male", Language: "Filipino", Country: "United States"},
	{Id: "voice-563", Name: "Ava Filipino", Gender: "Female", Language: "Filipino", Country: "United States"},
	{Id: "voice-564", Name: "Brian Filipino", Gender: "Male", Language: "Filipino", Country: "United States"},
	{Id: "voice-565", Name: "Emma Filipino", Gender: "Female", Language: "Filipino", Country: "United States"},
	{Id: "voice-566", Name: "Remy Filipino", Gender: "Male", Language: "Filipino", Country: "France"},
	{Id: "voice-567", Name: "Vivienne Filipino", Gender: "Female", Language: "Filipino", Country: "France"},
	{Id: "voice-568", Name: "Florian Filipino", Gender: "Male", Language: "Filipino", Country: "Germany"},
	{Id: "voice-569", Name: "Seraphina Filipino", Gender: "Female", Language: "Filipino", Country: "Germany"},
	{Id: "voice-570", Name: "Giuseppe Filipino", Gender: "Male", Language: "Filipino", Country: "Italy"},
	{Id: "voice-571", Name: "Hyunsu Filipino", Gender: "Male", Language: "Filipino", Country: "South Korea"},
	{Id: "voice-572", Name: "Thalita Filipino", Gender: "Female", Language: "Filipino", Country: "Brazil"},

	// Mexican Voices (voice-573 to voice-583)
	{Id: "voice-573", Name: "Andrew Mexican", Gender: "Male", Language: "Mexican", Country: "United States"},
	{Id: "voice-574", Name: "Ava Mexican", Gender: "Female", Language: "Mexican", Country: "United States"},
	{Id: "voice-575", Name: "Brian Mexican", Gender: "Male", Language: "Mexican", Country: "United States"},
	{Id: "voice-576", Name: "Emma Mexican", Gender: "Female", Language: "Mexican", Country: "United States"},
	{Id: "voice-577", Name: "Remy Mexican", Gender: "Male", Language: "Mexican", Country: "France"},
	{Id: "voice-578", Name: "Vivienne Mexican", Gender: "Female", Language: "Mexican", Country: "France"},
	{Id: "voice-579", Name: "Florian Mexican", Gender: "Male", Language: "Mexican", Country: "Germany"},
	{Id: "voice-580", Name: "Seraphina Mexican", Gender: "Female", Language: "Mexican", Country: "Germany"},
	{Id: "voice-581", Name: "Giuseppe Mexican", Gender: "Male", Language: "Mexican", Country: "Italy"},
	{Id: "voice-582", Name: "Hyunsu Mexican", Gender: "Male", Language: "Mexican", Country: "South Korea"},
	{Id: "voice-583", Name: "Thalita Mexican", Gender: "Female", Language: "Mexican", Country: "Brazil"},
}
